name: Claude PR Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          timeout_minutes: '60'
          allowed_tools: |
            Bash(yarn generate-image:*)
            Bash(NODE_ENV=production yarn build-only)
            Bash(bash -c:*)
            Bash(find:*)
            Bash(mkdir:*)
            Bash(mv:*)
            Bash(npm run swizzle:*)
            Bash(yarn swizzle:*)
            Bash(npx docusaurus swizzle:*)
            Bash(wget:*)
            Bash(sed:*)
            Bash(cp:*)
            Bash(fd:*)
            WebFetch(domain:stackoverflow.com)
            WebFetch(domain:docusaurus.io)
